CREATE TABLE TIME(
    ID NUMBER(10),
    NOME VARCHAR2(50)
);

CREATE TABLE JOGO (
    DATA DATE,
    PLACAR_CASA NUMBER(10),
    PLACAR_VISITANTE NUMBER(10)
);

CREATE TABLE JOGADOR (
    CPF NUMBER(11),
    NOME VARCHAR2(50)
);

INSERT INTO TIME (ID, NOME) VALUES (1, 'CRUZEIRO');
INSERT INTO TIME (ID, NOME) VALUES (2, 'ATLETICO');
INSERT INTO TIME (ID, NOME) VALUES (3, 'AMERICA');

INSERT INTO JOGO (DATA, PLACAR_CASA, PLACAR_VISITANTE) VALUES (TO_DATE('01/01/2019', 'DD/MM/YYYY'), 1, 2);
INSERT INTO JOGO (DATA, PLACAR_CASA, PLACAR_VISITANTE) VALUES (TO_DATE('02/11/2019', 'DD/MM/YYYY'), 2, 3);
INSERT INTO JOGO (DATA, PLACAR_CASA, PLACAR_VISITANTE) VALUES (TO_DATE('03/04/2019', 'DD/MM/YYYY'), 3, 4);

INSERT INTO JOGADOR (CPF, NOME) VALUES (12345678901, 'JOAO');
INSERT INTO JOGADOR (CPF, NOME) VALUES (23456789012, 'MARIA');
INSERT INTO JOGADOR (CPF, NOME) VALUES (34567890123, 'JOSE');

ALTER TABLE TIME ADD CONSTRAINT PK_TIME PRIMARY KEY (ID);
ALTER TABLE JOGADOR ADD CONSTRAINT PK_JOGADOR PRIMARY KEY (CPF);

ALTER TABLE JOGO ADD ID_CASA NUMBER(10);
ALTER TABLE JOGO ADD CONSTRAINT FK_JOGO_TIME_CASA FOREIGN KEY (ID_CASA) REFERENCES TIME(ID) ON DELETE CASCADE;

ALTER TABLE JOGO ADD ID_VISITANTE NUMBER(10);
ALTER TABLE JOGO ADD CONSTRAINT FK_JOGO_TIME_VISITANTE FOREIGN KEY (ID_VISITANTE) REFERENCES TIME(ID) ON DELETE CASCADE;

ALTER TABLE JOGADOR ADD ID_TIME NUMBER(10);
ALTER TABLE JOGADOR ADD CONSTRAINT FK_JOGADOR_TIME FOREIGN KEY (ID_TIME) REFERENCES TIME(ID);

UPDATE JOGO SET ID_CASA = 1, ID_VISITANTE = 2 WHERE DATA = TO_DATE('01/01/2019', 'DD/MM/YYYY');
UPDATE JOGO SET ID_CASA = 2, ID_VISITANTE = 3 WHERE DATA = TO_DATE('02/11/2019', 'DD/MM/YYYY');
UPDATE JOGO SET ID_CASA = 3, ID_VISITANTE = 1 WHERE DATA = TO_DATE('03/04/2019', 'DD/MM/YYYY');


UPDATE JOGADOR SET ID_TIME = 1 WHERE CPF = 12345678901;
UPDATE JOGADOR SET ID_TIME = 2 WHERE CPF = 23456789012;
UPDATE JOGADOR SET ID_TIME = 3 WHERE CPF = 34567890123;




ALTER TABLE JOGO ADD CONSTRAINT PK_JOGO PRIMARY KEY (DATA);

alter table jogo Drop CONSTRAINT PK_JOGO;

ALTER TABLE JOGO ADD CONSTRAINT PK_JOGO PRIMARY KEY (DATA, ID_CASA, ID_VISITANTE);

ALTER TABLE JOGADOR  MODIFY ID_TIME NUMBER(10) NOT NULL;

ALTER TABLE JOGADOR ADD CONSTRAINT UK_JOGADOR UNIQUE (NOME);

INSERT INTO JOGADOR (CPF, NOME, ID_TIME) VALUES (45678901234, 'JOAO', 1);

INSERT INTO JOGADOR (CPF, NOME, ID_TIME) VALUES (45678901234, '', 1);

INSERT INTO JOGO (DATA, PLACAR_CASA, PLACAR_VISITANTE, ID_CASA, ID_VISITANTE) VALUES (TO_DATE('01/01/2019', 'DD/MM/YYYY'), 1, 2, 1, 2);

INSERT INTO TIME (ID, NOME) VALUES (4, 'CRUZEIRO');